import { useState } from "react";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { BackButton } from "@/components/BackButton";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Search, MapPin, BookOpen, Star } from "lucide-react";
import { Link } from "react-router-dom";

interface Nayanar {
  number: number;
  nameTamil: string;
  nameEnglish: string;
  birthPlace: string;
  birthPlaceTamil: string;
  caste: string;
  period: string;
  story: string;
  storyTamil: string;
  associatedTemple: string;
  associatedTempleTamil: string;
  thevaramRef: string;
  highlight: string;
}

const NAYANMARS: Nayanar[] = [
  { number: 1, nameTamil: "திருநீலகண்ட நாயனார்", nameEnglish: "Thiruneelakanta Nayanar", birthPlace: "Thanjavur", birthPlaceTamil: "தஞ்சாவூர்", caste: "குயவர்", period: "7th Century", story: "A potter who mixed sacred ash into his clay. When his wife accidentally used regular clay, he cut off her hand but Shiva restored it, rewarding his devotion.", storyTamil: "திருநீறு கலந்து மண் பாண்டங்கள் செய்தவர். மனைவி தவறுதலாக சாதாரண மண் பயன்படுத்தியபோது, அவர் கையை வெட்டினார். சிவன் அருளால் கை மீண்டும் வந்தது.", associatedTemple: "Thanjavur Brihadeeswara Temple", associatedTempleTamil: "தஞ்சை பெரிய கோவில்", thevaramRef: "பெரியபுராணம் - சேக்கிழார்", highlight: "திருநீறு பக்தி" },
  { number: 2, nameTamil: "இயற்பகை நாயனார்", nameEnglish: "Iyarpakai Nayanar", birthPlace: "Kanchipuram", birthPlaceTamil: "காஞ்சிபுரம்", caste: "வணிகர்", period: "7th Century", story: "A merchant of Kanchipuram who gave everything to Shiva devotees. When a disguised Shiva asked for his wife, he agreed without hesitation, proving ultimate sacrifice.", storyTamil: "சிவனடியார்களுக்கு எல்லாவற்றையும் அளித்தவர். சிவன் மாறுவேடத்தில் வந்து மனைவியைக் கேட்டபோதும் தயங்காமல் ஒப்புக்கொண்டார்.", associatedTemple: "Ekambareswarar Temple, Kanchipuram", associatedTempleTamil: "ஏகாம்பரேஸ்வரர் கோவில், காஞ்சிபுரம்", thevaramRef: "பெரியபுராணம்", highlight: "தியாக சிகரம்" },
  { number: 3, nameTamil: "இளையான்குடி மாற நாயனார்", nameEnglish: "Ilayankudi Mara Nayanar", birthPlace: "Ilayankudi", birthPlaceTamil: "இளையான்குடி", caste: "வேளாளர்", period: "7th Century", story: "An agriculturist who dedicated all his harvest earnings to feeding Shiva devotees. Even in severe drought, he sold his possessions to continue service.", storyTamil: "விளைச்சல் வருமானம் முழுவதையும் சிவனடியார்களுக்கு உணவளிக்கப் பயன்படுத்தியவர். கடும் வறட்சியிலும் சொத்துக்களை விற்று சேவை தொடர்ந்தார்.", associatedTemple: "Ilayankudi Shiva Temple", associatedTempleTamil: "இளையான்குடி சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "அன்னதான சேவை" },
  { number: 4, nameTamil: "மெய்ப்பொருள் நாயனார்", nameEnglish: "Meiporul Nayanar", birthPlace: "Thirukkadavoor", birthPlaceTamil: "திருக்கடவூர்", caste: "அரசர்", period: "7th Century", story: "A Chola chieftain who was so devoted to Shiva bhaktas that when an enemy disguised as a Shaiva devotee came to kill him, he refused to fight back and attained moksha.", storyTamil: "சிவனடியார் வேடத்தில் வந்த எதிரியிடம் போர் செய்ய மறுத்து, சிவபக்தர்களைத் தாக்க மாட்டேன் என்று உயிர் நீத்தவர்.", associatedTemple: "Thirukkadavoor Amirthaghateswarar Temple", associatedTempleTamil: "திருக்கடவூர் அமிர்தகடேஸ்வரர் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "அடியார் பக்தி" },
  { number: 5, nameTamil: "விறல்மிண்ட நாயனார்", nameEnglish: "Viralminda Nayanar", birthPlace: "Thiruchengodu", birthPlaceTamil: "திருச்செங்கோடு", caste: "வேளாளர்", period: "7th Century", story: "A warrior who declared that Shiva's devotees should never bow to anyone else. He fought against those who disrespected Shaivites.", storyTamil: "சிவனடியார்கள் வேறு யாருக்கும் பணிய வேண்டாம் என்று அறிவித்தவர். சைவர்களை அவமதித்தவர்களை எதிர்த்துப் போரிட்டார்.", associatedTemple: "Arthanareeswara Temple, Thiruchengodu", associatedTempleTamil: "அர்த்தநாரீஸ்வரர் கோவில், திருச்செங்கோடு", thevaramRef: "பெரியபுராணம்", highlight: "சைவ வீரம்" },
  { number: 6, nameTamil: "அமர்நீதி நாயனார்", nameEnglish: "Amarneethi Nayanar", birthPlace: "Pazhaiyarai", birthPlaceTamil: "பழையாறை", caste: "வணிகர்", period: "7th Century", story: "A cloth merchant who offered the finest fabrics to Shiva devotees. When Shiva tested him by making a cloth disappear repeatedly, he offered everything he had.", storyTamil: "சிவனடியார்களுக்கு உயர்ந்த ஆடைகளை அளித்த துணி வணிகர். சிவன் சோதனையாக துணி மறையச் செய்தபோதும், தன் அனைத்தையும் அர்ப்பணித்தார்.", associatedTemple: "Pazhaiyarai Temple", associatedTempleTamil: "பழையாறை கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "ஆடை தானம்" },
  { number: 7, nameTamil: "சுந்தரர்", nameEnglish: "Sundarar", birthPlace: "Tirunavalur", birthPlaceTamil: "திருநாவலூர்", caste: "பிராமணர்", period: "8th Century", story: "One of the Moovar (three great poets). Called 'Tambiranaar Thozhan' (friend of Shiva). Composed Thiruthondar Thogai listing all 63 Nayanmars. Known for his passionate, personal relationship with Shiva.", storyTamil: "மூவர்களில் ஒருவர். 'தம்பிரான் தோழர்' என்று அழைக்கப்பட்டவர். 63 நாயன்மார்களை பட்டியலிட்ட திருத்தொண்டர் தொகை இயற்றியவர்.", associatedTemple: "Tirunavalur - Sundarar Birth Place Temple", associatedTempleTamil: "திருநாவலூர் சிவன் கோவில்", thevaramRef: "தேவாரம் - 7ம் திருமுறை, திருத்தொண்டர் தொகை", highlight: "தம்பிரான் தோழர்" },
  { number: 8, nameTamil: "திருநாவுக்கரசர்", nameEnglish: "Thirunavukkarasar (Appar)", birthPlace: "Thiruvamur", birthPlaceTamil: "திருவாமூர்", caste: "வேளாளர்", period: "7th Century", story: "Originally a Jain monk named Dharmasena, he converted to Shaivism after severe illness was cured by Shiva's grace. Survived multiple assassination attempts by Pallava king. One of the Moovar.", storyTamil: "முதலில் தர்மசேனர் என்ற ஜைன துறவி. கடும் நோயிலிருந்து சிவன் அருளால் குணமானார். பல்லவ மன்னரின் கொலை முயற்சிகளிலிருந்து தப்பினார். மூவர்களில் ஒருவர்.", associatedTemple: "Thiruvadigai Veerattaneswarar Temple", associatedTempleTamil: "திருவதிகை வீரட்டானேஸ்வரர் கோவில்", thevaramRef: "தேவாரம் - 4,5,6ம் திருமுறை", highlight: "நாவுக்கு அரசர்" },
  { number: 9, nameTamil: "குலச்சிறையார் நாயனார்", nameEnglish: "Kulachiraiyar Nayanar", birthPlace: "Pandya Nadu", birthPlaceTamil: "பாண்டிய நாடு", caste: "அமைச்சர்", period: "7th Century", story: "The chief minister of the Pandya king who helped spread Shaivism. He was instrumental in converting the Pandya king from Jainism to Shaivism along with Thirugnanasambandar.", storyTamil: "பாண்டிய மன்னரின் முதலமைச்சர். சமணத்திலிருந்து சைவத்திற்கு மன்னரை மாற்றுவதில் திருஞானசம்பந்தருடன் முக்கிய பங்கு வகித்தவர்.", associatedTemple: "Madurai Meenakshi Temple", associatedTempleTamil: "மதுரை மீனாட்சி கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சைவ பரவலுக்கு உதவியவர்" },
  { number: 10, nameTamil: "திருஞானசம்பந்தர்", nameEnglish: "Thirugnanasambandar", birthPlace: "Sirkali", birthPlaceTamil: "சீர்காழி", caste: "பிராமணர்", period: "7th Century", story: "Child prodigy who began composing Thevaram hymns at age 3 when Parvati fed him divine milk. Converted the Pandya king from Jainism. One of the Moovar. Attained Shiva at age 16 during his wedding.", storyTamil: "3 வயதில் பார்வதி தேவி பால் ஊட்டியபோது தேவாரம் பாடத் தொடங்கியவர். பாண்டிய மன்னரை சமணத்திலிருந்து மாற்றியவர். 16 வயதில் திருமணத்தில் சிவனை அடைந்தார்.", associatedTemple: "Sirkali Thoniappar Temple", associatedTempleTamil: "சீர்காழி தோணியப்பர் கோவில்", thevaramRef: "தேவாரம் - 1,2,3ம் திருமுறை", highlight: "பிள்ளையார் பக்தி, மூவர்" },
  { number: 11, nameTamil: "திருமூலர்", nameEnglish: "Thirumular", birthPlace: "Kailash (settled in Thiruvavaduthurai)", birthPlaceTamil: "கயிலாயம் (திருவாவடுதுறையில் தங்கியவர்)", caste: "யோகி", period: "Ancient", story: "A yogi from Kailash who came south. He entered the body of a dead cowherd Moolan to save the cows. Sat in meditation under a tree and composed the Thirumandiram (3000 verses) over 3000 years.", storyTamil: "கயிலாயத்திலிருந்து வந்த யோகி. இறந்த மூலன் உடலில் புகுந்து பசுக்களைக் காப்பாற்றினார். மரத்தடியில் 3000 ஆண்டுகள் தவமிருந்து திருமந்திரம் இயற்றினார்.", associatedTemple: "Thiruvavaduthurai Adheenam", associatedTempleTamil: "திருவாவடுதுறை ஆதீனம்", thevaramRef: "திருமந்திரம் - 10ம் திருமுறை", highlight: "திருமந்திரம் 3000" },
  { number: 12, nameTamil: "கல்லாடர்", nameEnglish: "Kalladar", birthPlace: "Kalladu", birthPlaceTamil: "கல்லாடு", caste: "பிராமணர்", period: "7th Century", story: "A great scholar who was an intimate friend of Sundarar. He composed hymns praising Shiva and was known for his deep knowledge of Shaiva scriptures.", storyTamil: "சுந்தரரின் நெருங்கிய நண்பர். சிவனைப் புகழ்ந்து பாடல்கள் இயற்றியவர். சைவ சாத்திரங்களில் ஆழ்ந்த அறிவு பெற்றவர்.", associatedTemple: "Kalladu Shiva Temple", associatedTempleTamil: "கல்லாடு சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சைவ அறிஞர்" },
  { number: 13, nameTamil: "கணநாதர் நாயனார்", nameEnglish: "Gananatha Nayanar", birthPlace: "Sivapuram", birthPlaceTamil: "சிவபுரம்", caste: "பிராமணர்", period: "7th Century", story: "Devoted to serving Shiva's devotees with flowers. He tended gardens to grow flowers exclusively for temple worship and the Shiva lingam.", storyTamil: "சிவலிங்கத்திற்கும் கோவில் வழிபாட்டிற்கும் மலர்கள் வளர்த்து அர்ப்பணித்தவர். சிவனடியார்களுக்கு மலர் சேவை செய்தவர்.", associatedTemple: "Sivapuram Temple", associatedTempleTamil: "சிவபுரம் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "மலர் சேவை" },
  { number: 14, nameTamil: "கூற்றுவ நாயனார்", nameEnglish: "Kootruva Nayanar", birthPlace: "Unknown", birthPlaceTamil: "அறியப்படவில்லை", caste: "அரசர்", period: "7th Century", story: "A king who waged war to protect Shaivism and ensure Shiva temples were properly maintained across his kingdom.", storyTamil: "சைவத்தைப் பாதுகாக்கவும் சிவன் கோவில்கள் சரியாகப் பராமரிக்கப்படவும் போர் செய்த மன்னர்.", associatedTemple: "Various Shiva Temples", associatedTempleTamil: "பல்வேறு சிவன் கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "சைவ காவலர்" },
  { number: 15, nameTamil: "மங்கையர்க்கரசியார்", nameEnglish: "Mangayarkarasi", birthPlace: "Madurai", birthPlaceTamil: "மதுரை", caste: "அரசி", period: "7th Century", story: "The Pandya queen who secretly practiced Shaivism while the king followed Jainism. She helped Thirugnanasambandar convert the king back to Shaivism.", storyTamil: "மன்னர் சமணத்தைப் பின்பற்றியபோது இரகசியமாக சைவம் கடைப்பிடித்த பாண்டிய ராணி. திருஞானசம்பந்தர் உதவியுடன் மன்னரை சைவத்திற்கு மாற்றினார்.", associatedTemple: "Madurai Meenakshi Temple", associatedTempleTamil: "மதுரை மீனாட்சி கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சைவ ராணி" },
  { number: 16, nameTamil: "கணம்புல்ல நாயனார்", nameEnglish: "Kanampulla Nayanar", birthPlace: "Kanampullanallur", birthPlaceTamil: "கணம்புல்லநல்லூர்", caste: "வேளாளர்", period: "7th Century", story: "A devotee who collected grass and sold it to earn money, using all earnings to buy oil for lighting Shiva temple lamps.", storyTamil: "புல் வெட்டி விற்று வரும் பணத்தில் சிவன் கோவில் விளக்கிற்கு எண்ணெய் வாங்கி ஏற்றியவர்.", associatedTemple: "Kanampullanallur Shiva Temple", associatedTempleTamil: "கணம்புல்லநல்லூர் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "தீப வழிபாடு" },
  { number: 17, nameTamil: "காரி நாயனார்", nameEnglish: "Kaari Nayanar", birthPlace: "Kazhumalam", birthPlaceTamil: "கழுமலம்", caste: "வேளாளர்", period: "7th Century", story: "A wealthy landlord who used all his wealth to maintain Shiva temples and feed devotees. He considered temple service as the highest dharma.", storyTamil: "தன் செல்வம் முழுவதையும் சிவன் கோவில் பராமரிப்பிற்கும் அடியார்களுக்கு உணவளிக்கவும் பயன்படுத்திய பெரும் நிலக்கிழார்.", associatedTemple: "Kazhumalam (Sirkali) Temple", associatedTempleTamil: "கழுமலம் (சீர்காழி) கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "கோவில் பராமரிப்பு" },
  { number: 18, nameTamil: "நின்றசீர் நெடுமாற நாயனார்", nameEnglish: "Nindraseer Nedumara Nayanar", birthPlace: "Madurai", birthPlaceTamil: "மதுரை", caste: "அரசர்", period: "7th Century", story: "The Pandya king Nedumaran who was converted from Jainism to Shaivism by Thirugnanasambandar. He became a great patron of Shiva temples.", storyTamil: "திருஞானசம்பந்தரால் சமணத்திலிருந்து சைவத்திற்கு மாற்றப்பட்ட பாண்டிய மன்னர் நெடுமாறன். சிவன் கோவில்களின் பெரும் ஆதரவாளர் ஆனார்.", associatedTemple: "Madurai Meenakshi Temple", associatedTempleTamil: "மதுரை மீனாட்சி கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சமணத்திலிருந்து சைவம்" },
  { number: 19, nameTamil: "வாயிலார் நாயனார்", nameEnglish: "Vayilar Nayanar", birthPlace: "Mylapore", birthPlaceTamil: "மயிலாப்பூர்", caste: "வணிகர்", period: "7th Century", story: "A devotee from Mylapore who served as a gatekeeper of the Shiva temple, ensuring only sincere devotees entered.", storyTamil: "சிவன் கோவில் வாயிலில் காவலராக நின்று உண்மையான பக்தர்கள் மட்டுமே நுழைவதை உறுதி செய்தவர்.", associatedTemple: "Kapaleeswarar Temple, Mylapore", associatedTempleTamil: "கபாலீஸ்வரர் கோவில், மயிலாப்பூர்", thevaramRef: "பெரியபுராணம்", highlight: "கோவில் காவலர்" },
  { number: 20, nameTamil: "முனையடுவார் நாயனார்", nameEnglish: "Munayaduvar Nayanar", birthPlace: "Neelanakka", birthPlaceTamil: "நீலநக்க", caste: "வேளாளர்", period: "7th Century", story: "A warrior devotee who fought in battles with Shiva's name on his lips. He dedicated all war victories to Lord Shiva.", storyTamil: "சிவன் பெயரைக் கூறிக்கொண்டே போரிட்ட வீர பக்தர். அனைத்து வெற்றிகளையும் சிவனுக்கு அர்ப்பணித்தார்.", associatedTemple: "Neelanakka Shiva Temple", associatedTempleTamil: "நீலநக்க சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சிவ வீரர்" },
  { number: 21, nameTamil: "கழற்சிங்க நாயனார்", nameEnglish: "Kazharsingha Nayanar", birthPlace: "Mangala Nadu", birthPlaceTamil: "மங்கல நாடு", caste: "அரசர்", period: "7th Century", story: "A king who always wore the sacred anklet (kazhal) and devoted his kingdom's resources to Shiva worship and temple building.", storyTamil: "எப்போதும் புனித கழலணிந்த மன்னர். நாட்டின் வளங்களை சிவ வழிபாட்டிற்கும் கோவில் கட்டுவதற்கும் அர்ப்பணித்தார்.", associatedTemple: "Mangala Nadu Shiva Temple", associatedTempleTamil: "மங்கல நாடு சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "கழல் அணிந்த மன்னர்" },
  { number: 22, nameTamil: "செருத்துணை நாயனார்", nameEnglish: "Seruthunai Nayanar", birthPlace: "Thanjavur", birthPlaceTamil: "தஞ்சாவூர்", caste: "அரசர்", period: "7th Century", story: "A Chola king who served as a warrior for Shaivism, protecting temples and devotees from threats.", storyTamil: "சைவத்திற்காக போராளியாகச் சேவையாற்றிய சோழ மன்னர். கோவில்களையும் பக்தர்களையும் அச்சுறுத்தல்களிலிருந்து காத்தார்.", associatedTemple: "Thanjavur Temples", associatedTempleTamil: "தஞ்சாவூர் கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "சோழ வீரர்" },
  { number: 23, nameTamil: "புகழ்ச்சோழ நாயனார்", nameEnglish: "Pugazhchola Nayanar", birthPlace: "Thanjavur", birthPlaceTamil: "தஞ்சாவூர்", caste: "அரசர்", period: "7th Century", story: "A Chola king known for his just rule and dedication to Shiva. He ensured that all temples in his kingdom were well-maintained.", storyTamil: "நீதியான ஆட்சிக்கும் சிவ பக்திக்கும் புகழ்பெற்ற சோழ மன்னர். நாட்டிலுள்ள அனைத்து கோவில்களும் நன்கு பராமரிக்கப்படுவதை உறுதி செய்தார்.", associatedTemple: "Thanjavur Region Temples", associatedTempleTamil: "தஞ்சாவூர் பகுதி கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "புகழ்பெற்ற சோழன்" },
  { number: 24, nameTamil: "நரசிங்க முனையரையர்", nameEnglish: "Narasinga Munairayar", birthPlace: "Thanjavur", birthPlaceTamil: "தஞ்சாவூர்", caste: "அரசர்", period: "7th Century", story: "A feudal chief who dedicated his life to Shiva worship and protection of Shaiva devotees in the Chola region.", storyTamil: "சோழ பகுதியில் சிவ வழிபாட்டிற்கும் சைவ அடியார்களின் பாதுகாப்பிற்கும் தன் வாழ்வை அர்ப்பணித்த குறுநில மன்னர்.", associatedTemple: "Chola Region Temples", associatedTempleTamil: "சோழ பகுதி கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "சிவ பாதுகாவலர்" },
  { number: 25, nameTamil: "அதிபத்தர் நாயனார்", nameEnglish: "Adipattar Nayanar", birthPlace: "Nagapattinam", birthPlaceTamil: "நாகப்பட்டினம்", caste: "மீனவர்", period: "7th Century", story: "A fisherman who offered the first and best fish of every catch to Shiva. When he once caught a golden fish, he offered it to Shiva without hesitation.", storyTamil: "ஒவ்வொரு முறையும் மீன் பிடிக்கும்போது முதல் மற்றும் சிறந்த மீனை சிவனுக்கு அளித்தவர். தங்க மீன் பிடிக்கப்பட்டபோது தயங்காமல் அதை சிவனுக்கு அர்ப்பணித்தார்.", associatedTemple: "Nagapattinam Kayarohanaswami Temple", associatedTempleTamil: "நாகப்பட்டினம் காயாரோகணசுவாமி கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "மீன் காணிக்கை" },
  { number: 26, nameTamil: "கலிக்கம்ப நாயனார்", nameEnglish: "Kalikkamba Nayanar", birthPlace: "Pennadam", birthPlaceTamil: "பெண்ணாடம்", caste: "வேளாளர்", period: "7th Century", story: "A devotee who served Shiva by maintaining the temple precincts clean and adorned with kolam patterns every day.", storyTamil: "ஒவ்வொரு நாளும் கோவில் வளாகத்தை சுத்தமாகவும் கோலம் போட்டும் அலங்கரித்து சிவனுக்கு சேவை செய்தவர்.", associatedTemple: "Pennadam Shiva Temple", associatedTempleTamil: "பெண்ணாடம் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "கோவில் தூய்மை" },
  { number: 27, nameTamil: "கலிய நாயனார்", nameEnglish: "Kaliya Nayanar", birthPlace: "Mylapore", birthPlaceTamil: "மயிலாப்பூர்", caste: "வணிகர்", period: "7th Century", story: "A rich merchant who spent all his wealth building Shiva temples and conducting elaborate pujas.", storyTamil: "தன் செல்வம் முழுவதையும் சிவன் கோவில்கள் கட்டுவதிலும் விரிவான பூஜைகள் நடத்துவதிலும் செலவிட்ட செல்வந்த வணிகர்.", associatedTemple: "Kapaleeswarar Temple, Mylapore", associatedTempleTamil: "கபாலீஸ்வரர் கோவில், மயிலாப்பூர்", thevaramRef: "பெரியபுராணம்", highlight: "கோவில் கட்டுதல்" },
  { number: 28, nameTamil: "சத்தி நாயனார்", nameEnglish: "Satti Nayanar", birthPlace: "Varinjiyam", birthPlaceTamil: "வாரிஞ்சியம்", caste: "வணிகர்", period: "7th Century", story: "A devotee known for his absolute faith in Shiva. He would accept any hardship as Shiva's grace.", storyTamil: "சிவனிடம் முழு நம்பிக்கை கொண்ட பக்தர். எந்த கஷ்டத்தையும் சிவன் அருளாக ஏற்றுக்கொண்டார்.", associatedTemple: "Varinjiyam Shiva Temple", associatedTempleTamil: "வாரிஞ்சியம் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "முழு சரணாகதி" },
  { number: 29, nameTamil: "ஐயடிகள் காடவர்கோன் நாயனார்", nameEnglish: "Aiyadigal Kadavarkon Nayanar", birthPlace: "Kanchipuram", birthPlaceTamil: "காஞ்சிபுரம்", caste: "அரசர்", period: "7th Century", story: "A Pallava prince who renounced his throne to become a Shiva devotee. He wandered temples singing Shiva's praises.", storyTamil: "அரியணையை துறந்து சிவ பக்தர் ஆன பல்லவ இளவரசர். கோவில்களுக்குச் சென்று சிவன் புகழ் பாடி அலைந்தார்.", associatedTemple: "Kailasanathar Temple, Kanchipuram", associatedTempleTamil: "கைலாசநாதர் கோவில், காஞ்சிபுரம்", thevaramRef: "பெரியபுராணம்", highlight: "அரசை துறந்தவர்" },
  { number: 30, nameTamil: "கணநாயகர் (கணனாதர்)", nameEnglish: "Gananayanar", birthPlace: "Erattai Theevam", birthPlaceTamil: "இரட்டைத் தீவம்", caste: "வேளாளர்", period: "7th Century", story: "A village leader who organized community worship of Shiva and ensured every household participated in temple festivals.", storyTamil: "சிவ வழிபாட்டை ஒழுங்கமைத்த கிராமத் தலைவர். ஒவ்வொரு குடும்பமும் கோவில் திருவிழாக்களில் பங்கேற்பதை உறுதி செய்தார்.", associatedTemple: "Erattai Theevam Shiva Temple", associatedTempleTamil: "இரட்டைத் தீவம் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சமூக வழிபாடு" },
  { number: 31, nameTamil: "கூற்றுவ நாயனார்", nameEnglish: "Kootruva Nayanar (II)", birthPlace: "Seyyur", birthPlaceTamil: "செய்யூர்", caste: "அரசர்", period: "7th Century", story: "Protected Shaivism with military might and ensured the prosperity of Shiva temples in the southern regions.", storyTamil: "இராணுவ வலிமையால் சைவத்தைப் பாதுகாத்து, தென் பகுதிகளில் சிவன் கோவில்களின் செழிப்பை உறுதி செய்தார்.", associatedTemple: "Seyyur Shiva Temple", associatedTempleTamil: "செய்யூர் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சிவ படை" },
  { number: 32, nameTamil: "புகழ்த்துணை நாயனார்", nameEnglish: "Pugazhthunai Nayanar", birthPlace: "Thanjavur Region", birthPlaceTamil: "தஞ்சாவூர் பகுதி", caste: "வேளாளர்", period: "7th Century", story: "A devotee celebrated for organizing grand festivals at Shiva temples and supporting traveling saints.", storyTamil: "சிவன் கோவில்களில் மாபெரும் திருவிழாக்களை நடத்தியும் பயணம் செய்யும் சந்நியாசிகளுக்கு உதவியும் புகழ்பெற்ற பக்தர்.", associatedTemple: "Thanjavur Region Temples", associatedTempleTamil: "தஞ்சாவூர் பகுதி கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "திருவிழா ஏற்பாடு" },
  { number: 33, nameTamil: "கோட்புலி நாயனார்", nameEnglish: "Kotpuli Nayanar", birthPlace: "Nattham", birthPlaceTamil: "நாட்டம்", caste: "அரசர்", period: "7th Century", story: "A fierce warrior who was as brave as a tiger (puli) in battle. He fought to protect Shiva devotees from persecution.", storyTamil: "போரில் புலி போல் வீரமிக்க போர்வீரர். சிவ பக்தர்களை துன்புறுத்தலிலிருந்து காக்க போர் செய்தார்.", associatedTemple: "Nattham Shiva Temple", associatedTempleTamil: "நாட்டம் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "வீரத்தின் புலி" },
  { number: 34, nameTamil: "பொய்யடிமையில்லாத புலவர்", nameEnglish: "Poyyaadimayillatha Pulavar", birthPlace: "Various", birthPlaceTamil: "பலர்", caste: "பலர்", period: "Various", story: "This refers to the collective group of Shiva devotees who were absolutely sincere in their devotion without any falsehood.", storyTamil: "பொய்யான அடிமைத்தனம் இல்லாத உண்மையான சிவ பக்தர்கள் கூட்டம்.", associatedTemple: "All Shiva Temples", associatedTempleTamil: "அனைத்து சிவன் கோவில்கள்", thevaramRef: "திருத்தொண்டர் தொகை", highlight: "உண்மை பக்தி" },
  { number: 35, nameTamil: "புலிபாணி நாயனார்", nameEnglish: "Pulipani Nayanar", birthPlace: "Unknown", birthPlaceTamil: "அறியப்படவில்லை", caste: "அறிஞர்", period: "7th Century", story: "A great siddha who mastered yoga and tantra, using his powers exclusively for Shiva worship.", storyTamil: "யோகமும் தந்திரமும் கற்ற சித்தர். தன் சக்திகளை சிவ வழிபாட்டிற்கு மட்டுமே பயன்படுத்தியவர்.", associatedTemple: "Various Siddhar Temples", associatedTempleTamil: "பல்வேறு சித்தர் கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "சித்த யோகி" },
  { number: 36, nameTamil: "மாணிக்கவாசகர்", nameEnglish: "Manikkavasagar", birthPlace: "Thiruvathavoor", birthPlaceTamil: "திருவாதவூர்", caste: "பிராமணர்", period: "9th Century", story: "Author of Thiruvasagam. He was the Prime Minister of the Pandya king who spent the king's horse-purchasing money on a Shiva temple. Shiva appeared as a horse-trader to save him. His poetry is considered the most emotionally moving in Tamil.", storyTamil: "திருவாசகம் ஆசிரியர். பாண்டிய மன்னரின் முதலமைச்சர். குதிரை வாங்கும் பணத்தை சிவன் கோவிலுக்கு செலவிட்டவர். சிவனே குதிரை வியாபாரியாக வந்து காப்பாற்றினார்.", associatedTemple: "Thiruperunthurai (Avudaiyarkoil)", associatedTempleTamil: "திருப்பெருந்துறை (ஆவுடையார்கோவில்)", thevaramRef: "திருவாசகம் - 8ம் திருமுறை", highlight: "திருவாசகம் ஆசிரியர்" },
  { number: 37, nameTamil: "அரிவாட்டாய நாயனார்", nameEnglish: "Arivattaya Nayanar", birthPlace: "Poonthurai", birthPlaceTamil: "பூந்துறை", caste: "வேளாளர்", period: "7th Century", story: "A devotee who used a sickle (arivaal) to cut grass and flowers for Shiva worship every day without fail.", storyTamil: "ஒவ்வொரு நாளும் தவறாமல் அரிவாளால் புல்லும் மலர்களும் வெட்டி சிவ வழிபாட்டிற்கு அளித்தவர்.", associatedTemple: "Poonthurai Shiva Temple", associatedTempleTamil: "பூந்துறை சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "அன்றாட சேவை" },
  { number: 38, nameTamil: "ஆனாய நாயனார்", nameEnglish: "Aanaya Nayanar", birthPlace: "Mangalur", birthPlaceTamil: "மங்களூர்", caste: "இடையர்", period: "7th Century", story: "A cowherd who played divine music on his flute for Shiva while tending cattle. His music was so pure that Shiva appeared before him.", storyTamil: "மாடுகளை மேய்க்கும்போது சிவனுக்காக புல்லாங்குழல் வாசித்த இடையர். அவரது இசை மிகவும் தூய்மையானதால் சிவன் அவர் முன் தோன்றினார்.", associatedTemple: "Mangalur Shiva Temple", associatedTempleTamil: "மங்களூர் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "புல்லாங்குழல் பக்தி" },
  { number: 39, nameTamil: "முருக நாயனார்", nameEnglish: "Muruga Nayanar", birthPlace: "Pumpuhar", birthPlaceTamil: "பூம்புகார்", caste: "வேளாளர்", period: "7th Century", story: "A devotee who offered thousands of puja lamps to Shiva every day. Despite his name being Muruga, his devotion was entirely to Shiva.", storyTamil: "ஒவ்வொரு நாளும் ஆயிரக்கணக்கான பூஜா விளக்குகளை சிவனுக்கு ஏற்றியவர். முருகன் என்ற பெயர் இருந்தாலும் சிவனிடம் முழு பக்தி.", associatedTemple: "Pumpuhar Shiva Temple", associatedTempleTamil: "பூம்புகார் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "ஆயிரம் விளக்கு" },
  { number: 40, nameTamil: "உருத்திர பசுபதி நாயனார்", nameEnglish: "Rudra Pasupati Nayanar", birthPlace: "Thalaichchangadu", birthPlaceTamil: "தலைச்சங்காடு", caste: "பிராமணர்", period: "7th Century", story: "A scholar who chanted Rudram 1008 times daily and spent his entire life in Shiva worship and meditation.", storyTamil: "தினமும் 1008 முறை ருத்ரம் ஓதிய அறிஞர். தன் முழு வாழ்க்கையையும் சிவ வழிபாட்டிலும் தியானத்திலும் கழித்தார்.", associatedTemple: "Thalaichchangadu Shiva Temple", associatedTempleTamil: "தலைச்சங்காடு சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "ருத்ர ஜபம்" },
  { number: 41, nameTamil: "திருநாளைப்போவார் நாயனார்", nameEnglish: "Thirunalaippovar Nayanar (Nandanar)", birthPlace: "Adhanur", birthPlaceTamil: "ஆதனூர்", caste: "புலையர்", period: "8th Century", story: "Born in a lower caste, he yearned to worship at Chidambaram but was denied entry. He would watch from outside saying 'tomorrow I will go.' Shiva made Nandi move aside so Nandanar could see the deity. Finally walked through sacred fire and was purified.", storyTamil: "கீழ் ஜாதியில் பிறந்தவர். சிதம்பரத்தில் வழிபட விரும்பினார் ஆனால் நுழைய அனுமதிக்கப்படவில்லை. 'நாளை போவேன்' என்று வெளியிலிருந்து பார்ப்பார். சிவன் நந்தியை நகர்த்தி நாயனாரை தரிசிக்க வைத்தார்.", associatedTemple: "Chidambaram Nataraja Temple", associatedTempleTamil: "சிதம்பரம் நடராஜர் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சாதி தடையை உடைத்தவர்" },
  { number: 42, nameTamil: "திருக்குறிப்புத்தொண்டர்", nameEnglish: "Thirukurippu Thondar", birthPlace: "Kanchipuram", birthPlaceTamil: "காஞ்சிபுரம்", caste: "வண்ணார்", period: "7th Century", story: "A washerman who washed clothes for Shiva devotees for free. When Shiva tested him by sending endless dirty clothes in rain, he washed them all without complaint.", storyTamil: "சிவனடியார்களின் ஆடைகளை இலவசமாகத் துவைத்தவர். சிவன் சோதனையாக மழையில் முடிவில்லாத அழுக்கு ஆடைகளை அனுப்பியபோதும் புகார் இல்லாமல் துவைத்தார்.", associatedTemple: "Ekambareswarar Temple, Kanchipuram", associatedTempleTamil: "ஏகாம்பரேஸ்வரர் கோவில், காஞ்சிபுரம்", thevaramRef: "பெரியபுராணம்", highlight: "வண்ணார் தொண்டு" },
  { number: 43, nameTamil: "சண்டேசுவர நாயனார்", nameEnglish: "Chandeswarar Nayanar", birthPlace: "Seynalur", birthPlaceTamil: "செய்ஞலூர்", caste: "பிராமணர்", period: "Ancient", story: "As a boy, he worshipped a sand Shiva lingam with milk from the cows he tended. When his father kicked the milk offering, young Chandeswarar cut off his father's leg with an axe. Shiva made him the lord of all offerings.", storyTamil: "சிறுவனாக இருக்கும்போது, மேய்ச்சல் பசுக்களின் பாலால் மணல் லிங்கத்தை வழிபட்டார். தந்தை பால் காணிக்கையை உதைத்தபோது, கோடரியால் தந்தையின் காலை வெட்டினார். சிவன் அவரை சண்டேஸ்வரராக்கினார்.", associatedTemple: "Seynalur / All Shiva Temples (Chandeswarar shrine)", associatedTempleTamil: "செய்ஞலூர் / அனைத்து சிவன் கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "சிவனுக்கு பிரசாத அதிபதி" },
  { number: 44, nameTamil: "திருநாவுக்கரசர் சுவாமிகள் தாயார்", nameEnglish: "Tilakavatiyar (Appar's sister)", birthPlace: "Thiruvamur", birthPlaceTamil: "திருவாமூர்", caste: "வேளாளர்", period: "7th Century", story: "The elder sister of Appar who prayed intensely to Shiva to bring her brother back from Jainism. Her prayers were answered when Appar fell ill and was cured by Shiva.", storyTamil: "அப்பரின் மூத்த சகோதரி. தன் தம்பியை சமணத்திலிருந்து மீட்க சிவனிடம் தீவிரமாக பிரார்த்தனை செய்தார். அப்பர் நோய்வாய்ப்பட்டு சிவனால் குணமாக்கப்பட்டார்.", associatedTemple: "Thiruvamur Shiva Temple", associatedTempleTamil: "திருவாமூர் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சகோதரி பக்தி" },
  { number: 45, nameTamil: "சாக்கிய நாயனார்", nameEnglish: "Sakkiya Nayanar", birthPlace: "Thiruchengattankudi", birthPlaceTamil: "திருச்செங்காட்டங்குடி", caste: "வணிகர்", period: "7th Century", story: "Originally a Buddhist who converted to Shaivism. He threw stones at Buddhist and Jain idols and worshipped only Shiva.", storyTamil: "முதலில் புத்த மதத்தைப் பின்பற்றியவர், பின்னர் சைவத்திற்கு மாறினார். புத்த, சமண சிலைகள் மீது கற்களை எறிந்து சிவனை மட்டுமே வழிபட்டார்.", associatedTemple: "Thiruchengattankudi Temple", associatedTempleTamil: "திருச்செங்காட்டங்குடி கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "புத்தமதத்தில் இருந்து சைவம்" },
  { number: 46, nameTamil: "சிறப்புலி நாயனார்", nameEnglish: "Sirappuli Nayanar", birthPlace: "Thiruchengodu", birthPlaceTamil: "திருச்செங்கோடு", caste: "வேளாளர்", period: "7th Century", story: "A devoted farmer who offered all his produce to Shiva before keeping any for himself or family.", storyTamil: "தனக்கோ குடும்பத்திற்கோ வைத்துக்கொள்ளும் முன் தன் விளைபொருள் அனைத்தையும் சிவனுக்கு அர்ப்பணித்த விவசாயி.", associatedTemple: "Thiruchengodu Temple", associatedTempleTamil: "திருச்செங்கோடு கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "முதல் அறுவடை சிவனுக்கு" },
  { number: 47, nameTamil: "சிறுத்தொண்ட நாயனார்", nameEnglish: "Sirutthonda Nayanar", birthPlace: "Thiruchangattankudi", birthPlaceTamil: "திருச்செங்காட்டங்குடி", caste: "அரசர்", period: "7th Century", story: "A Pallava general who fed Shiva devotees. Shiva tested him by asking him to cook his own son as food. He obeyed, but Shiva restored the child to life.", storyTamil: "சிவனடியார்களுக்கு உணவளித்த பல்லவ சேனாபதி. சிவன் சோதனையாக தன் மகனையே உணவாகச் சமைக்கச் சொன்னார். கீழ்ப்படிந்தார், சிவன் குழந்தையை உயிர்ப்பித்தார்.", associatedTemple: "Thiruchangattankudi Satthinathar Temple", associatedTempleTamil: "திருச்செங்காட்டங்குடி சத்திநாதர் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "உச்ச தியாகம்" },
  { number: 48, nameTamil: "கழறிற்றறிவார் நாயனார் (சேரமான் பெருமாள்)", nameEnglish: "Cheraman Perumal Nayanar", birthPlace: "Kerala (Kodungallur)", birthPlaceTamil: "கேரளா (கொடுங்கல்லூர்)", caste: "அரசர்", period: "8th Century", story: "The Chera king and close friend of Sundarar. He followed Sundarar to Kailash when Sundarar was called by Shiva, leaving his kingdom behind.", storyTamil: "சேர மன்னர், சுந்தரரின் நெருங்கிய நண்பர். சிவன் சுந்தரரை அழைத்தபோது, தன் நாட்டை விட்டு சுந்தரருடன் கயிலாயத்திற்கு சென்றார்.", associatedTemple: "Thiruvanchikulam Temple, Kerala", associatedTempleTamil: "திருவஞ்சிக்குளம் கோவில், கேரளா", thevaramRef: "பெரியபுராணம்", highlight: "சேர மன்னர், நட்பின் சிகரம்" },
  { number: 49, nameTamil: "எறிபத்த நாயனார்", nameEnglish: "Eripatha Nayanar", birthPlace: "Karuvur", birthPlaceTamil: "கருவூர்", caste: "வேளாளர்", period: "7th Century", story: "A fierce devotee who would attack anyone who showed disrespect to Shiva or his devotees, even if it meant violence.", storyTamil: "சிவனையோ அவர் பக்தர்களையோ அவமதிப்பவர்களைத் தாக்கும் தீவிர பக்தர்.", associatedTemple: "Karuvur Pasupatheswarar Temple", associatedTempleTamil: "கருவூர் பசுபதீஸ்வரர் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சிவ கோபம்" },
  { number: 50, nameTamil: "ஏனாதிநாத நாயனார்", nameEnglish: "Enadinatha Nayanar", birthPlace: "Eyanur", birthPlaceTamil: "எயினூர்", caste: "படை வீரர்", period: "7th Century", story: "A military commander who ensured sacred ash (Vibhuti) was applied by all soldiers. He saw Shiva in every warrior.", storyTamil: "அனைத்து வீரர்களும் விபூதி அணிவதை உறுதி செய்த படைத் தளபதி. ஒவ்வொரு போர்வீரனிலும் சிவனைக் கண்டார்.", associatedTemple: "Eyanur Shiva Temple", associatedTempleTamil: "எயினூர் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "படை வீரர் சிவபக்தர்" },
  { number: 51, nameTamil: "கணம்புல்ல நாயனார்", nameEnglish: "Kanampulla Nayanar (II)", birthPlace: "Thanjavur", birthPlaceTamil: "தஞ்சாவூர்", caste: "வேளாளர்", period: "7th Century", story: "A humble devotee who collected thorny bushes to light temple lamps, enduring pain from thorns for Shiva's service.", storyTamil: "கோவில் விளக்குகளை எரிக்க முட்புதர்களை சேகரித்தவர். சிவன் சேவைக்காக முட்களின் வலியை பொறுத்துக்கொண்டார்.", associatedTemple: "Thanjavur Shiva Temple", associatedTempleTamil: "தஞ்சாவூர் சிவன் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "தீப ஒளி சேவை" },
  { number: 52, nameTamil: "தண்டியடிகள் நாயனார்", nameEnglish: "Thandiyadigal Nayanar", birthPlace: "Thanjavur", birthPlaceTamil: "தஞ்சாவூர்", caste: "பிராமணர்", period: "7th Century", story: "A devotee who walked with a staff (thandi) visiting every Shiva temple, never staying in one place for more than a day.", storyTamil: "தடியுடன் நடந்து ஒவ்வொரு சிவன் கோவிலையும் தரிசித்தவர். ஒரு இடத்தில் ஒரு நாளுக்கு மேல் தங்கியதில்லை.", associatedTemple: "All Shiva Temples (Pilgrimage)", associatedTempleTamil: "அனைத்து சிவன் கோவில்கள் (யாத்திரை)", thevaramRef: "பெரியபுராணம்", highlight: "கோவில் யாத்திரை" },
  { number: 53, nameTamil: "மூர்க்க நாயனார்", nameEnglish: "Moorkka Nayanar", birthPlace: "Pudukkottai", birthPlaceTamil: "புதுக்கோட்டை", caste: "வேளாளர்", period: "7th Century", story: "Despite being called 'stubborn' (moorkka), he was stubbornly devoted to Shiva, never wavering in his worship routine.", storyTamil: "'பிடிவாதமானவர்' என்று அழைக்கப்பட்டாலும், சிவ பக்தியில் உறுதியாக இருந்தவர். வழிபாட்டு வழக்கத்தில் ஒருபோதும் தள்ளாடாதவர்.", associatedTemple: "Pudukkottai Region Temples", associatedTempleTamil: "புதுக்கோட்டை பகுதி கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "உறுதியான பக்தி" },
  { number: 54, nameTamil: "சோமசிமாற நாயனார்", nameEnglish: "Somasimara Nayanar", birthPlace: "Madurai", birthPlaceTamil: "மதுரை", caste: "அரசர்", period: "7th Century", story: "A Pandya king who performed extensive Shiva worship and temple renovations throughout the Pandya kingdom.", storyTamil: "பாண்டிய நாடு முழுவதும் விரிவான சிவ வழிபாடும் கோவில் புனரமைப்பும் செய்த பாண்டிய மன்னர்.", associatedTemple: "Madurai Meenakshi Temple", associatedTempleTamil: "மதுரை மீனாட்சி கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "கோவில் புனரமைப்பு" },
  { number: 55, nameTamil: "சாக்கிய நாயனார் (II)", nameEnglish: "Sakkiya Nayanar (II)", birthPlace: "Thirupazhanam", birthPlaceTamil: "திருப்பழனம்", caste: "வணிகர்", period: "7th Century", story: "Devotee who abandoned Buddhism and embraced Shaivism wholeheartedly, becoming a model of sincere conversion.", storyTamil: "புத்த மதத்தை விட்டு முழு மனதுடன் சைவத்தை ஏற்றுக்கொண்டவர். உண்மையான மாற்றத்தின் முன்மாதிரி.", associatedTemple: "Thirupazhanam Temple", associatedTempleTamil: "திருப்பழனம் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "சைவ மாற்றம்" },
  { number: 56, nameTamil: "இசைஞானியார்", nameEnglish: "Isaignani (Mother of Sambandar)", birthPlace: "Sirkali", birthPlaceTamil: "சீர்காழி", caste: "பிராமணர்", period: "7th Century", story: "Mother of Thirugnanasambandar. She raised her son in deep devotion to Shiva and supported his divine mission from childhood.", storyTamil: "திருஞானசம்பந்தரின் தாயார். தன் மகனை சிவ பக்தியில் வளர்த்து, சிறுவயது முதலே அவரது தெய்வீகப் பணியை ஆதரித்தார்.", associatedTemple: "Sirkali Thoniappar Temple", associatedTempleTamil: "சீர்காழி தோணியப்பர் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "தாயின் பக்தி" },
  { number: 57, nameTamil: "இடங்கழி நாயனார்", nameEnglish: "Idangazhi Nayanar", birthPlace: "Thiruvidaimarudur", birthPlaceTamil: "திருவிடைமருதூர்", caste: "வேளாளர்", period: "7th Century", story: "A devotee who measured grain with a special measure (idangazhi) and always gave extra portions to Shiva's temple.", storyTamil: "தானிய அளவு பாத்திரத்தால் அளந்து எப்போதும் சிவன் கோவிலுக்கு கூடுதல் பகுதிகளை வழங்கிய பக்தர்.", associatedTemple: "Thiruvidaimarudur Temple", associatedTempleTamil: "திருவிடைமருதூர் கோவில்", thevaramRef: "பெரியபுராணம்", highlight: "தானிய தானம்" },
  { number: 58, nameTamil: "செருத்துணை நாயனார் (II)", nameEnglish: "Seruthunai Nayanar (II)", birthPlace: "Chola Nadu", birthPlaceTamil: "சோழ நாடு", caste: "வீரர்", period: "7th Century", story: "A warrior who fought alongside Shiva devotees against oppressors, considering battle service as worship.", storyTamil: "அடக்குமுறையாளர்களுக்கு எதிராக சிவ பக்தர்களுடன் போரிட்ட வீரர். போர் சேவையை வழிபாடாகக் கருதினார்.", associatedTemple: "Chola Nadu Temples", associatedTempleTamil: "சோழ நாடு கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "போர் வழிபாடு" },
  { number: 59, nameTamil: "புகழ்ச்சோழ நாயனார் (II)", nameEnglish: "Pugazhchola Nayanar (II)", birthPlace: "Kumbakonam", birthPlaceTamil: "கும்பகோணம்", caste: "அரசர்", period: "7th Century", story: "A Chola prince who built numerous temples and endowed them with lands and resources for perpetual worship.", storyTamil: "பல கோவில்கள் கட்டி, நிரந்தர வழிபாட்டிற்காக நிலங்களும் வளங்களும் வழங்கிய சோழ இளவரசர்.", associatedTemple: "Kumbakonam Temples", associatedTempleTamil: "கும்பகோணம் கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "கோவில் எடுப்பு" },
  { number: 60, nameTamil: "நம்பியாண்டார் நம்பி", nameEnglish: "Nambiyandar Nambi", birthPlace: "Thirunaraiyur", birthPlaceTamil: "திருநரையூர்", caste: "பிராமணர்", period: "11th Century", story: "The compiler of the twelve Thirumurai, the canonical collection of Shaiva Tamil hymns. Without him, much of Thevaram and other works would have been lost.", storyTamil: "பன்னிரு திருமுறைகளை தொகுத்தவர். சைவ தமிழ் பதிகங்களின் நியம தொகுப்பு. இவர் இல்லையென்றால் தேவாரம் உள்ளிட்ட பல படைப்புகள் அழிந்திருக்கும்.", associatedTemple: "Thirunaraiyur Temple", associatedTempleTamil: "திருநரையூர் கோவில்", thevaramRef: "பன்னிரு திருமுறை தொகுப்பாளர்", highlight: "திருமுறை தொகுப்பு" },
  { number: 61, nameTamil: "திருக்குறிப்புத்தொண்டர் நாயனார்", nameEnglish: "Thirukurippu Thondar Nayanar (II)", birthPlace: "Kanchipuram", birthPlaceTamil: "காஞ்சிபுரம்", caste: "வண்ணார்", period: "7th Century", story: "A washerman who understood Shiva's subtle gestures (kurippu). He dedicated his life to washing the clothes of all Shiva devotees.", storyTamil: "சிவனின் நுட்பமான சைகைகளைப் புரிந்தவர். சிவ பக்தர்கள் அனைவரின் ஆடைகளையும் துவைப்பதில் வாழ்வை அர்ப்பணித்தார்.", associatedTemple: "Kanchipuram Shiva Temples", associatedTempleTamil: "காஞ்சிபுரம் சிவன் கோவில்கள்", thevaramRef: "பெரியபுராணம்", highlight: "தொண்டு செய்தவர்" },
  { number: 62, nameTamil: "சேக்கிழார்", nameEnglish: "Sekkizhar", birthPlace: "Kundrathur", birthPlaceTamil: "குன்றத்தூர்", caste: "வேளாளர்", period: "12th Century", story: "The author of Periyapuranam (12th Thirumurai), which tells the stories of all 63 Nayanmars. He was the chief minister of Chola king Kulottunga II and composed this masterpiece to replace Jain literature.", storyTamil: "பெரியபுராணம் (12ம் திருமுறை) ஆசிரியர். 63 நாயன்மார்களின் கதைகளை சொல்லும் இந்நூலை இயற்றியவர். சோழ மன்னர் இரண்டாம் குலோத்துங்கனின் முதலமைச்சர்.", associatedTemple: "Kundrathur Shiva Temple / All Temples", associatedTempleTamil: "குன்றத்தூர் சிவன் கோவில்", thevaramRef: "பெரியபுராணம் - 12ம் திருமுறை ஆசிரியர்", highlight: "பெரியபுராணம் ஆசிரியர்" },
  { number: 63, nameTamil: "கோச்செங்கட் சோழ நாயனார்", nameEnglish: "Kochengat Chola Nayanar", birthPlace: "Thanjavur", birthPlaceTamil: "தஞ்சாவூர்", caste: "அரசர்", period: "2nd Century", story: "One of the earliest Chola kings and Nayanmars. He is credited with building 70 Shiva temples (Madakkoil style). Born blind but gained sight through Shiva's grace. Known as 'Kallen Koil Cholan'.", storyTamil: "மிகப் பழமையான சோழ மன்னர்களில் ஒருவர். 70 சிவன் கோவில்கள் (மடக்கோவில் பாணி) கட்டியவர். பிறவிக்குருடராக பிறந்து சிவன் அருளால் பார்வை பெற்றார். 'கல்லன் கோவில் சோழன்' என அறியப்படுபவர்.", associatedTemple: "70 Madakkoil Temples across Tamil Nadu", associatedTempleTamil: "தமிழ்நாடு முழுவதும் 70 மடக்கோவில்கள்", thevaramRef: "பெரியபுராணம், சிலப்பதிகாரம்", highlight: "70 கோவில் கட்டிய மன்னர்" },
];

export default function NayanmarsPage() {
  const [search, setSearch] = useState("");
  const [expandedId, setExpandedId] = useState<number | null>(null);

  const filtered = NAYANMARS.filter(n =>
    n.nameTamil.includes(search) ||
    n.nameEnglish.toLowerCase().includes(search.toLowerCase()) ||
    n.birthPlaceTamil.includes(search) ||
    n.birthPlace.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container py-6 space-y-6">
        <BackButton />

        <div className="text-center space-y-2">
          <h1 className="text-3xl md:text-4xl font-bold font-tamil text-gradient-sacred">
            அறுபத்திமூன்று நாயன்மார்கள்
          </h1>
          <p className="text-muted-foreground">63 Nayanmars — The Great Shaivite Saints</p>
          <p className="text-sm text-muted-foreground max-w-2xl mx-auto">
            சேக்கிழாரின் பெரியபுராணத்தில் போற்றப்படும் 63 சிவனடியார்கள். இவர்களின் வாழ்க்கை கதைகள் சிவபக்தியின் உச்சத்தை காட்டுகின்றன.
          </p>
        </div>

        <div className="relative max-w-md mx-auto">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="நாயன்மார் தேடுக... / Search Nayanar..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-10"
          />
        </div>

        <p className="text-center text-sm text-muted-foreground">
          காட்டப்படுவது: {filtered.length} / 63 நாயன்மார்கள்
        </p>

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {filtered.map((n) => {
            const isExpanded = expandedId === n.number;
            return (
              <Card
                key={n.number}
                className="cursor-pointer hover:shadow-lg transition-shadow border-sacred/20"
                onClick={() => setExpandedId(isExpanded ? null : n.number)}
              >
                <CardHeader className="pb-2">
                  <div className="flex items-start justify-between">
                    <Badge variant="outline" className="text-xs bg-sacred/10 text-sacred border-sacred/30">
                      #{n.number}
                    </Badge>
                    <Badge variant="secondary" className="text-xs">{n.period}</Badge>
                  </div>
                  <CardTitle className="text-lg font-tamil leading-relaxed">{n.nameTamil}</CardTitle>
                  <p className="text-sm text-muted-foreground">{n.nameEnglish}</p>
                </CardHeader>
                <CardContent className="space-y-2 text-sm">
                  <div className="flex items-center gap-1 text-muted-foreground">
                    <MapPin className="h-3 w-3" />
                    <span>{n.birthPlaceTamil} ({n.birthPlace})</span>
                  </div>
                  <Badge variant="outline" className="text-xs">{n.highlight}</Badge>

                  {isExpanded && (
                    <div className="mt-3 pt-3 border-t space-y-3 animate-in fade-in">
                      <div>
                        <p className="font-semibold text-xs text-muted-foreground mb-1">கதை (Tamil)</p>
                        <p className="font-tamil text-sm leading-relaxed">{n.storyTamil}</p>
                      </div>
                      <div>
                        <p className="font-semibold text-xs text-muted-foreground mb-1">Story (English)</p>
                        <p className="text-sm leading-relaxed">{n.story}</p>
                      </div>
                      <div className="flex items-start gap-1">
                        <Star className="h-3 w-3 mt-0.5 text-sacred" />
                        <div>
                          <p className="font-semibold text-xs text-muted-foreground">தொடர்புடைய கோவில்</p>
                          <p className="font-tamil text-sm">{n.associatedTempleTamil}</p>
                          <p className="text-xs text-muted-foreground">{n.associatedTemple}</p>
                        </div>
                      </div>
                      <div className="flex items-start gap-1">
                        <BookOpen className="h-3 w-3 mt-0.5 text-sacred" />
                        <div>
                          <p className="font-semibold text-xs text-muted-foreground">இலக்கிய குறிப்பு</p>
                          <p className="text-xs">{n.thevaramRef}</p>
                        </div>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      </main>
      <Footer />
    </div>
  );
}
