ALTER TABLE temples ADD COLUMN IF NOT EXISTS is_navagraha BOOLEAN DEFAULT FALSE;
ALTER TABLE temples ADD COLUMN IF NOT EXISTS navagraha_planet TEXT;
ALTER TABLE temples ADD COLUMN IF NOT EXISTS navagraha_order INTEGER;